# Database configuration
database:
  url: postgres://postgres:postgres@postgres:5432/textanalyzer?sslmode=disable

# Storage configuration
storage:
  path: ./storage/files

# Server configuration
server:
  port: 50051